export const SET_ENTERED_VALUE = 'SET_ENTERED_VALUE'
export const UPDATE_HISTORY_ITEM = 'UPDATE_HISTORY_ITEM'
export const ADD_HISTORY_ITEM = 'ADD_HISTORY_ITEM'
export const EDIT_HISTORY_ITEM = 'EDIT_HISTORY_ITEM'